{% set name = "roseau-load-flow" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/roseau_load_flow-{{ version }}.tar.gz
  sha256: a077934286576f40127ef0a791942c2e7f5ec9c34b5d5d7e80f12bfabd7baf64

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - numpy >=1.21.5
    - pandas >=1.4.0
    - geopandas >=0.10.2
    - shapely >=2.0.0
    - regex >=2022.1.18
    - requests >=2.28.1
    - pint >=0.21.0
    - typing_extensions >=4.6.2
    - rich >=13.5.1
    - pyproj >=3.3.0
    - matplotlib-base >=3.7.2
    - networkx >=3.0.0

test:
  imports:
    - roseau
    - roseau.load_flow
    - roseau.load_flow.io
    - roseau.load_flow.models
    - roseau.load_flow.utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/RoseauTechnologies/Roseau_Load_Flow/
  summary: Highly capable three-phase load flow solver
  license: BSD-3-Clause
  license_file: LICENSE.md
  doc_url: https://roseautechnologies.github.io/Roseau_Load_Flow/

extra:
  recipe-maintainers:
    - benoit9126
